### ISSUE TITLE
Running kafka-setup.sh multiple times leads to 403

### ISSUE THREAD

**Issue by MichalCervenansky** [5733d9e2be6485d52ffa08870cabdee0/sandbox#498]
While running the Demo I came across error 403 from kafka-setup.sh. Caused by `"reason":"Max allowed number:5 of service accounts for user:mcervena@redhat.com has reached"`

From 
`ocm get /api/kafkas_mgmt/v1/service_accounts --parameter size=1000 | jq '.items[]|select(.owner=="mcervena@redhat.com")'`
I see that script always creates new mk-local-mc instances instead of using existing ones. Printing 
`sa_count=$( rhoas service-account list -o json | jq -rc ".items[] | select( .name == \"${sa_name}\" )" | wc -l )`
 gives me 0. I don't see why.

After deleting all instances by `rhoas service-account delete --id SERVICE_ACCOUNT_ID` I am able to sucessfully run kafka-setup.sh and the third run hits the 5 service account limit.

**Comment by Aakanksha0311** [comment]
"403 Forbidden" error was faced by me as well while running Demo.md. I used the ocm command(mentioned above by Michal)to list and then rhoas(mentioned above by Michal) to delete the existing service accounts.
After this it works fine for me.

**Comment by robpblake** [comment]
@MichalCervenansky Can you please create an issue for us in JIRA to document this fix. We don't use GitHub Issues.

cheers,

Rob

**Comment by MichalCervenansky** [comment]
Closed and moved to Jira
https://issues.redhat.com/browse/MGDOBR-470
